"""empty message

Revision ID: 618cbe172f64
Revises: 
Create Date: 2025-09-29 23:29:29.486060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '618cbe172f64'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('taskid', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('taskid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tasks')
    # ### end Alembic commands ###
